image: node:16.13

stages:
	- install
  - build
  - deploy

install:
  stage: install
  script:
    - npm ci
	cache:
		key:
			-	package-json.lock
		files:
			node_modules/
		policy:
			push

build:
  only:
    refs:
      - development
  stage: build
  variables:
    NX_FIREBASE_API_KEY: "$NX_FIREBASE_API_KEY"
    NX_FIREBASE_AUTH_DOMAIN: "$NX_FIREBASE_AUTH_DOMAIN"
    NX_FIREBASE_DATA_BASE_URL: "$NX_FIREBASE_DATA_BASE_URL"
    NX_FIREBASE_PROJECT_ID: "$NX_FIREBASE_PROJECT_ID"
    NX_FIREBASE_STORAGE_BUCKET: "$NX_FIREBASE_STORAGE_BUCKET"
    NX_FIREBASE_MESSAGING_SENDER_ID: "$NX_FIREBASE_MESSAGING_SENDER_ID"
    NX_FIREBASE_APP_ID: "$NX_FIREBASE_APP_ID"
    FIREBASE_TOKEN: "$FIREBASE_TOKEN"
  script:
    - npm run build:all
	cache:
		key:
			-	package-json.lock
		files:
			- node_modules/
		policy:	pull
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/apps

deploy:
  before_script:
    - npm i -g firebase-tools
  only:
    - development
  stage: deploy
  script:
    - firebase deploy --only hosting:material-hosting --token $FIREBASE_TOKEN
