# deploy-firestore:
#   stage: deploy
#   script:
#     - firebase deploy --only firestore --token $FIREBASE_DEPLOY_KEY
#   only:
#     refs:
#       - development
#     changes:
#       - firebase-config/firestore.rules
#       - firebase-config/firestore.indexes.json

# deploy-functions:
#   stage: deploy
#   script:
#     - cd functions
#     - npm install
#     - cd ..
#     - firebase deploy --only functions --token $FIREBASE_DEPLOY_KEY
#   only:
#     refs:
#       - development
#     changes:
#       - functions/**/*

prod-hosting:
  stage: deploy
  script:
    - echo $NX_FIREBASE_API_KEY
    - npm i
  	- npm i -g firebase-tools
    - npm run build
    - firebase deploy --only hosting --token $FIREBASE_DEPLOY_KEY
  only:
    - development
  # environment:
    # NX_FIREBASE_API_KEY: "$NX_FIREBASE_API_KEY"
    # NX_FIREBASE_AUTH_DOMAIN: "$NX_FIREBASE_AUTH_DOMAIN"
    # NX_FIREBASE_DATA_BASE_URL: "$NX_FIREBASE_DATA_BASE_URL"
    # NX_FIREBASE_PROJECT_ID: "$NX_FIREBASE_PROJECT_ID"
    # NX_FIREBASE_STORAGE_BUCKET: "$NX_FIREBASE_STORAGE_BUCKET"
    # NX_FIREBASE_MESSAGING_SENDER_ID: "$NX_FIREBASE_MESSAGING_SENDER_ID"
    # NX_FIREBASE_APP_ID: "$NX_FIREBASE_APP_ID"

