image: node:16.13

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  only:
    refs:
      - development
  stage: build
  variables:
    NX_FIREBASE_API_KEY: "$NX_FIREBASE_API_KEY"
    NX_FIREBASE_AUTH_DOMAIN: "$NX_FIREBASE_AUTH_DOMAIN"
    NX_FIREBASE_DATA_BASE_URL: "$NX_FIREBASE_DATA_BASE_URL"
    NX_FIREBASE_PROJECT_ID: "$NX_FIREBASE_PROJECT_ID"
    NX_FIREBASE_STORAGE_BUCKET: "$NX_FIREBASE_STORAGE_BUCKET"
    NX_FIREBASE_MESSAGING_SENDER_ID: "$NX_FIREBASE_MESSAGING_SENDER_ID"
    NX_FIREBASE_APP_ID: "$NX_FIREBASE_APP_ID"
    FIREBASE_TOKEN: "$FIREBASE_TOKEN"
  script:
    - npm run build:material
  artifacts:
    expire_in: 1 hour
    paths:
      - build


deploy:
	before_script:
    - npm i -g firebase-tools
  only:
    - development
  stage: deploy
  script:
    - firebase deploy --only hosting:material-hosting --token $FIREBASE_TOKEN
