stages:
  - build_dev
  - deploy_dev

build_dev:
  only:
    refs:
      - development
  stage: build
  variables:
    NX_FIREBASE_API_KEY: "$NX_FIREBASE_API_KEY"
		NX_FIREBASE_AUTH_DOMAIN: "$NX_FIREBASE_AUTH_DOMAIN"
		NX_FIREBASE_DATA_BASE_URL: "$NX_FIREBASE_DATA_BASE_URL"
		NX_FIREBASE_PROJECT_ID: "$NX_FIREBASE_PROJECT_ID"
		NX_FIREBASE_STORAGE_BUCKET: "$NX_FIREBASE_STORAGE_BUCKET"
		NX_FIREBASE_MESSAGING_SENDER_ID: "$NX_FIREBASE_MESSAGING_SENDER_ID"
		NX_FIREBASE_APP_ID: "$NX_FIREBASE_APP_ID"
  script:
    - echo $NX_FIREBASE_API_KEY
		- echo $NX_FIREBASE_AUTH_DOMAIN
		- echo $NX_FIREBASE_DATA_BASE_URL
		- echo $NX_FIREBASE_PROJECT_ID
		- echo $NX_FIREBASE_STORAGE_BUCKET
		- echo $NX_FIREBASE_MESSAGING_SENDER_ID
		- echo $NX_FIREBASE_APP_ID
		- echo "Building application"
    - npm run build:material
  artifacts:
    expire_in: 1 hour
    paths:
      - build

deploy_dev:
  only:
    refs:
      - development
  stage: deploy
  script:
		- firebase use $NX_FIREBASE_PROJECT_ID
		- firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY --only hosting"

